chore: add peerid @bhgomes
farcasterxyz/hub-monorepo pull request #1005
Opened 2023-06-02 15:20 UTC by bhgomes

## Motivation

Add a peerid for farcaster mainnet hubs.

## Change Summary

- Added a new allowed peer to the `allowedPeers.mainnet.ts` file in the `apps/hubble/src` directory.
- The new peer has the following address: `12D3KooWNLshuXk4x2gacFTMEJjMGGFxPjpHg5KcV88KoqJP7dDR`.
- No other changes were made.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] PR has a [changeset](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#35-adding-changesets)
- [ ] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [x] PR does not require changes to the [protocol](https://github.com/farcasterxyz/protocol)
- [x] All [commits have been signed](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#22-signing-commits)

2023-06-14 06:43 UTC, varunsrin requested changes
you'll also need to rebase this

2023-06-14 06:43 UTC, varunsrin commented on apps/hubble/src/allowedPeers.mainnet.ts
> +  '12D3KooWNLshuXk4x2gacFTMEJjMGGFxPjpHg5KcV88KoqJP7dDR', // @bhgomes
could you add your farcaster username here instead of your github name? this is so we can contact you for feedback

2023-06-15 06:27 UTC, bhgomes commented on apps/hubble/src/allowedPeers.mainnet.ts
> +  '12D3KooWNLshuXk4x2gacFTMEJjMGGFxPjpHg5KcV88KoqJP7dDR', // @bhgomes
same username :)

2023-06-15 06:41 UTC, closed without merging

2023-06-15 06:46 UTC, bhgomes commented
Closed in favor of https://github.com/farcasterxyz/hub-monorepo/pull/1019. I messed up the rebase here.