Rust via Neon
farcasterxyz/hub-monorepo pull request #1191
Opened 2023-07-26 20:33 UTC by adityapk00

This is a temporary PR to test jest on github actions. It will not be merged

2023-07-27 17:11 UTC, varunsrin requested changes
We need to add docs in a few places: 

1. In `apps/hubble/www/docs/index.md` need change Typescript to Typescript + Rust
2. In `apps/hubble/www/docs/intro/hubble.md` need to do same as above
3. In `apps/hubble/www/docs/intro/install.md` we only show you how to install with Docker, but we should add a section at the bottom called Install from Source, which walks through all the steps needed.

2023-07-27 17:20 UTC, sanjayprabhu commented on packages/core/src/validations.ts
> +    const signatureIsValid = nativeEd25519Verify(signature, hash, signer);
I assume this is already covered by tests somewhere, but would be good to have explicit tests for this function for valid and invalid signatures.

2023-07-27 17:46 UTC, adityapk00 commented on packages/core/src/validations.ts
> +    const signatureIsValid = nativeEd25519Verify(signature, hash, signer);
Added new tests

2023-07-27 17:46 UTC, adityapk00 commented
> Nice, this looks good. Why did it improve the full iteration over messages so much? Or was this actually the `validateOrRevokeMessages` job?

Yes, it's not the iteration itself that's faster, but the `validateOrRevoke` is 10x faster

2023-07-27 17:47 UTC, adityapk00 commented
> We need to add docs in a few places:
> 
>     1. In `apps/hubble/www/docs/index.md` need change Typescript to Typescript + Rust
> 
>     2. In `apps/hubble/www/docs/intro/hubble.md` need to do same as above
> 
>     3. In `apps/hubble/www/docs/intro/install.md` we only show you how to install with Docker, but we should add a section at the bottom called Install from Source, which walks through all the steps needed.
@varunsrin - Added docs here: https://github.com/farcasterxyz/hub-monorepo/pull/1191/files#diff-25665ec3091d368ad2c870599c191d03a53aecd9de087de3eec696d0d6a40316. 

Let me know if they look good

2023-07-28 15:47 UTC, varunsrin commented on apps/hubble/www/docs/intro/install.md
> +- [Node.js 20+](https://nodejs.org/en/download/releases)
the package.json in the root only requires >= 18.7, should we update this?

2023-07-28 15:47 UTC, varunsrin commented on apps/hubble/www/docs/intro/install.md
> +- [Anvil](https://book.getfoundry.sh/getting-started/installation#using-foundryup)
should we just say install foundry? it's not clear from going to that page that anvil is a part of foundry

2023-07-28 15:47 UTC, varunsrin commented on apps/hubble/www/docs/intro/install.md
> +1. `yarn idenfity create` to create a ID
typo: identity

2023-07-28 15:47 UTC, varunsrin commented on apps/hubble/www/docs/intro/install.md
> +To upgrade hubble, simply `git pull` to get the latest version of the source and run the build steps again. (`yarn install && yarn build`)
we should encourage people to find the latest tagged version and pull it, instead of just pulling main

2023-07-28 16:18 UTC, varunsrin commented on packages/core/src/addon/Cargo.toml
> +ed25519-dalek = "1.0.1"
curious, why ed25519-dalek over the ed25519 library?

2023-07-28 16:25 UTC, adityapk00 commented on packages/core/src/addon/Cargo.toml
> +ed25519-dalek = "1.0.1"
The rust ed25519 doesn't contain an implementation, just the pluggable traits. (https://docs.rs/ed25519/latest/ed25519/)

Also,  ed25519-dalek supports batch verification, which is much faster (But we're not using this yet)

2023-07-28 16:25 UTC, varunsrin commented on packages/core/src/addon/src/lib.rs
> +        Err(_) => return Ok(cx.number(0)),
i've run into weird bugs with crypto libraries where sometimes passing a zero value into a signature checker cases it to pass (i think this was in the JS ecdsa library) 

it might be a good idea for safety to either explicitly fail, or add a rust level test showing that this would fail so its obvious to the reader.

2023-07-28 16:26 UTC, adityapk00 commented on packages/core/src/addon/Cargo.toml
> +ed25519-dalek = "1.0.1"
That said, there are other implementations of the ed25519 crate, but ed25519-dakel is supposedly the fastest.

2023-07-28 16:27 UTC, varunsrin commented on packages/core/src/addon/addon.js
> +function nativeEd25519Verify(signature, hash, signer) {
it might be good to add somewhere in the CONTRIBUTING.md file a pointer to the neon and maybe 1-2 lines explaining how it works, so people can read more.

2023-07-28 16:27 UTC, varunsrin approved these changes

2023-07-28 16:28 UTC, adityapk00 commented on packages/core/src/addon/src/lib.rs
> +        Err(_) => return Ok(cx.number(0)),
I've added a test that passes in 0-length signature and signer and assert that it fails (here: https://github.com/farcasterxyz/hub-monorepo/pull/1191/files#diff-9638c830dcbfdb1806a033158d1e5a95def793d5eac9606b3664d1609005254fR963)

2023-07-28 16:32 UTC, merged