Viem v2
farcasterxyz/hub-monorepo pull request #2181
Opened 2024-07-15 04:13 UTC by darrylyeo

## Why is this change needed?

Upgrade [`viem`](https://viem.sh/) to the latest version. More context in [this cast](https://warpcast.com/v/0xffa5abfb).

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [ ] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] PR has a [changeset](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#35-adding-changesets)
- [ ] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] PR includes [documentation](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#32-writing-docs) if necessary.

2024-07-15 07:16 UTC, dalechyn reviewed
Why did all of the `<clientInstance>.<instanceActionMethod>(...)` changed to `<globalActionMethod>(<clientInstance>, ...)`?

I.e: `testClient.mine(...)` changed to `mine(testClient)`.

AFAIK those methods are still accessible.
What's the motivation behind this?

2024-07-15 07:16 UTC, dalechyn commented on packages/hub-nodejs/examples/contract-signatures/package.json
> +}
Needs a newline?

2024-07-15 15:38 UTC, darrylyeo commented
> Why did all of the `<clientInstance>.<instanceActionMethod>(...)` changed to `<globalActionMethod>(<clientInstance>, ...)`?

I chose to switch to this pattern because:

1. it allows for tree-shaking (see [docs](https://viem.sh/docs/clients/custom#tree-shaking)).
2. it makes it easier to derive types for helper functions using e.g. `Parameters<>` rather than chasing down the exact helper type + params used internally by the library.

2024-07-15 19:30 UTC, varunsrin commented
@darrylyeo we have some lints failing, which are blocking the tests from running

2024-07-15 19:35 UTC, varunsrin requested changes

2024-07-15 19:35 UTC, varunsrin commented on apps/hubble/src/eth/l2EventsProvider.test.ts
> +      // @ts-ignore
@darrylyeo can you add more context about why the ignore is necessary?

2024-07-15 19:35 UTC, varunsrin commented on apps/hubble/src/eth/l2EventsProvider.ts
> +      // @ts-ignore
why is an ignore necessary here?

2024-07-15 19:35 UTC, varunsrin commented on apps/hubble/src/eth/l2EventsProvider.ts
> +        // @ts-ignore
Is the ignore necessary here?

2024-07-15 19:35 UTC, varunsrin commented on .changeset/violet-steaks-rule.md
> +"@farcaster/hub-nodejs": minor
should be a patch version. 

minor versions are for breaking upgrades in farcaster's versioning system

2024-07-17 07:03 UTC, darrylyeo commented
Okay, managed to find the right type parameters to satisfy the underlying viem actions. Had a lot of trouble earlier getting viem's conditional return types to match up as TypeScript was unable to infer the parameters from the loosely-typed helper methods.

2024-07-17 23:55 UTC, Wazzymandias commented on .changeset/violet-steaks-rule.md
> +"@farcaster/hub-nodejs": minor
also need to run `yarn lint` to format

2024-07-26 23:53 UTC, CassOnMars commented on apps/hubble/src/eth/l2EventsProvider.ts
> +    if (this._publicClient.transport["transports"]?.[0]?.value?.["url"]) {
why did this check get added prior to iterating?

2024-07-27 00:48 UTC, darrylyeo commented on apps/hubble/src/eth/l2EventsProvider.ts
> +    if (this._publicClient.transport["transports"]?.[0]?.value?.["url"]) {
It was an edge case caught by the type system – depending on how this class is initialized, the transport object is not necessarily guaranteed to be an [`HttpTransport`](https://viem.sh/docs/clients/transports/http.html).

2024-07-27 17:03 UTC, darrylyeo commented
For anyone curious, I wrote about my experience implementing TypeScript type parameters here:
https://warpcast.com/darrylyeo/0x01dbdbaa

2024-07-29 21:59 UTC, merged