Update CONTRIBUTING.md
farcasterxyz/hub-monorepo pull request #2334
Opened 2024-09-26 14:59 UTC by vadimka14

add a dot where it is missing

## Why is this change needed?

you need to follow the culture of writing

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [ ] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] PR has a [changeset](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#35-adding-changesets)
- [ ] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] PR includes [documentation](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#32-writing-docs) if necessary.

2024-09-26 17:11 UTC, sds requested changes

2024-09-26 17:11 UTC, sds commented on CONTRIBUTING.md
> +### 3.2. Writing Docs
Header numbering don't end with a period. From ChatGPT:

> 1.	**Clarity and Consistency**: The period in “3.2” is already separating the section number from the subsection. Adding another period at the end (i.e., “3.2.”) could cause confusion, as it is redundant and unnecessary.
> 2.	**Style Guides**: Common style guides, such as the Chicago Manual of Style and APA, recommend numbering headers without a trailing period unless it serves a specific purpose (e.g., in some legal or technical documents, though even these often omit the extra period).
> 
> In most cases, “3.2” without the trailing period is the correct and preferred format.

2024-09-27 10:44 UTC, vadimka14 commented on CONTRIBUTING.md
> +### 3.2. Writing Docs
then why "3.1." and "3.3." is with dot. Then i`ll make new commit

2024-10-01 14:22 UTC, sds commented
Other PR was merged—thank you. Can you update this one so we can merge it as well?

2024-10-01 14:30 UTC, vadimka14 commented
> Other PR was merged—thank you. Can you update this one so we can merge it as well?

 I have already made another commit with the proposed changes. Can you tell me what and how I should update in this commit?

2024-10-01 14:32 UTC, vadimka14 commented
maybe should I close it?

2024-10-01 17:01 UTC, closed without merging