0 shared tsconfig
farcasterxyz/hub-monorepo pull request #523
Opened 2023-02-04 03:21 UTC by outricked

## Motivation

Describe why this issue should be fixed and link to any relevant design docs, issues or other relevant items.

## Change Summary

Describe the changes being made in 1-2 concise sentences.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [ ] The title of this PR adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] The PR has been tagged with the appropriate change type label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] Changes to the protocol specification have been merged

## Additional Context

If this is a relatively large or complex change, provide more details here that will help reviewers

2023-02-04 03:33 UTC, outricked commented
@varunsrin lmk what u think!

2023-02-05 20:29 UTC, varunsrin requested changes

2023-02-05 20:29 UTC, varunsrin commented on apps/hubble/CHANGELOG.md
> +## 1.0.6
i dont think we should bump versions for dev configuration changes, but will tag @pfletcherhill to weigh in here

2023-02-05 20:29 UTC, varunsrin commented on apps/hubble/package.json
> +    "tsconfig": "*",
this should be a devDependency instead of a regular dependency wherever possible

2023-02-07 19:54 UTC, outricked commented
@varunsrin updated.

2023-02-08 17:49 UTC, varunsrin requested changes
looks great! just a couple small changes before its ready to merge

2023-02-08 17:49 UTC, varunsrin commented on packages/protobufs/tsconfig.json
> +  "extends": "tsconfig/package-config.json",
i don't think w need the `exclude` property in line 7 anymore here since it is defined in package-config.json, which this inherits from

2023-02-08 17:49 UTC, varunsrin commented on packages/tsconfig/package-config.json
> +  "extends": "tsconfig/base.json",
can we call this file `packages-config` instead of `package-config`

2023-02-08 17:49 UTC, varunsrin commented on packages/tsconfig/package-config.json
> +  "exclude": ["build", "node_modules", "jest.config.ts"]
we can add `"include": ["src/index.ts"]` and remove it from all the other files safely

2023-02-08 17:50 UTC, varunsrin commented
@outricked there seems to be a build failure in the docker file that may need some investigation

https://github.com/farcasterxyz/hubble/actions/runs/4117667949/jobs/7129294508

2023-02-09 07:44 UTC, outricked commented on packages/tsconfig/package-config.json
> +  "exclude": ["build", "node_modules", "jest.config.ts"]
I tried this, Unfortunately, it fails to build, because it resolves the path to the tsconfig that contains the include. In fact,  I think tsconfig is configured like this for inheritance: https://www.typescriptlang.org/tsconfig#extends

There's an unresolved issue on the typescript page: https://github.com/microsoft/TypeScript/issues/29172.

I think each tsconfig has to have their own include, exclude, outDir, etc. Anything that has a relative path.

Seems like this change won't accomplish what the issue asked for? @varunsrin

2023-02-27 17:21 UTC, varunsrin commented
@outricked still planning on merging this? happy to keep assigned to you if you are

2023-02-27 17:32 UTC, outricked commented
@varunsrin Hey! I can take a look and finish this up. Just wasn't sure if you still wanted the change given the tsconfig constraints

2023-02-27 21:35 UTC, outricked commented
@varunsrin updated dockerfile which should hopefully fix the docker build error earlier. Also moved everything into the appropriate folders.

2023-02-28 02:33 UTC, varunsrin commented
sadly, docker still seems unhappy. 

you can speed up the loop by building the docker container locally, that way you don't need to wait for ci to run to see if it works or not.

2023-03-04 21:42 UTC, outricked commented
Hey @varunsrin ! Got my image to build properly. Checked the docker's folder structures and it seems pretty good. I'm running into an error when running the container that I can't figure out. Any ideas? Error logs

```
2023-03-04 13:19:21 yarn run v1.22.19
2023-03-04 13:19:21 $ tsx src/cli.ts start --rpc-port 8080 --ip 0.0.0.0 --gossip-port 9090 --eth-rpc-url https://eth-goerli.g.alchemy.com/v2/IvjMoCKt1hT66f9OJoL_dMXypnvQYUdd --network 1
2023-03-04 13:19:25 node:internal/process/promises:288
2023-03-04 13:19:25             triggerUncaughtException(err, true /* fromPromise */);
2023-03-04 13:19:25             ^
2023-03-04 13:19:25 
2023-03-04 13:19:25 [Error: ENOENT: no such file or directory, open '/home/node/app/apps/hubble/.hub/default_id.protobuf'] {
2023-03-04 13:19:25   errno: -2,
2023-03-04 13:19:25   code: 'ENOENT',
2023-03-04 13:19:25   syscall: 'open',
2023-03-04 13:19:25   path: '/home/node/app/apps/hubble/.hub/default_id.protobuf'
2023-03-04 13:19:25 }
2023-03-04 13:19:25 
2023-03-04 13:19:25 Node.js v18.14.2
2023-03-04 13:19:25 error Command failed with exit code 1.
2023-03-04 13:19:25 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2023-03-05 02:10 UTC, outricked commented
Seems like I'm missing some .hub file that's referenced by hub.config.ts? But unclear how I get that

2023-03-06 04:57 UTC, varunsrin commented
yeah, its the identity file. right now you have to [generate it from the command line](https://github.com/farcasterxyz/hubble/blob/2a2eb365599fd077145774b2b9d90755e481fc45/apps/hubble/package.json#L25) and [pass it into the container](https://github.com/farcasterxyz/hubble/blob/2a2eb365599fd077145774b2b9d90755e481fc45/Dockerfile#L84)

2023-03-09 19:45 UTC, varunsrin commented
@outricked looks like its working now? just needs a rebase

2023-03-09 20:36 UTC, outricked commented
@varunsrin Sorry been a busy week. Let me double check that the container is running locally and then I will rebase!

2023-03-10 22:16 UTC, outricked commented
confirmed that the container is working locally and processing events! rebased master @varunsrin 🚀

2023-03-30 22:28 UTC, outricked commented
@varunsrin just reupdated to fix merge conflicts. I'd love to get this merged and fix this issue!

2023-07-04 19:01 UTC, varunsrin commented
closing since we're moving rome tools

2023-07-04 19:01 UTC, closed without merging