chore: add a peer for mainnet
farcasterxyz/hub-monorepo pull request #881
Opened 2023-04-17 20:57 UTC by manan19

## Motivation

Describe why this issue should be fixed and link to any relevant design docs, issues or other relevant items.

## Change Summary

Describe the changes being made in 1-2 concise sentences.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [ ] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] PR has a [changeset](../CONTRIBUTING.md#35-adding-changesets)
- [ ] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] PR does not require changes to the [protocol](https://github.com/farcasterxyz/protocol)
- [ ] All [commits have been signed](../CONTRIBUTING.md#22-signing-commits)

## Additional Context

If this is a relatively large or complex change, provide more details here that will help reviewers

2023-04-18 18:46 UTC, varunsrin requested changes
you'll need to [sign your commits ](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#22-signing-commits) for the changes to be accepted

2023-04-18 18:46 UTC, varunsrin commented on .changeset/curvy-worms-tie.md
> +---
changeset can be removed since this is just a configuration change (but thanks for being thorough!)

2023-04-19 18:16 UTC, manan19 commented
@varunsrin signed again.

2023-04-19 19:08 UTC, varunsrin approved these changes

2023-04-19 20:06 UTC, merged