Request to run a mainnet Hub
farcasterxyz/hub-monorepo pull request #902
Opened 2023-04-21 07:55 UTC by Meyanis95

## Motivation

I already have a testnet hub running and want to switch for mainnet.

## Change Summary

Adding my hub to the list of eligible hubs.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [ ] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] PR has a [changeset](../CONTRIBUTING.md#35-adding-changesets)
- [ ] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] PR does not require changes to the [protocol](https://github.com/farcasterxyz/protocol)
- [ ] All [commits have been signed](../CONTRIBUTING.md#22-signing-commits)

2023-04-21 19:12 UTC, pfletcherhill requested changes

2023-04-21 19:12 UTC, pfletcherhill commented on apps/hubble/src/allowedPeers.mainnet.ts
> +  '12D3KooWEr4WoKduAQg8VJSgwcNsqptbdkSQLw1ceEr8oSBQurJX', // @meyanisxyz
I don't see a farcaster user for the fname "meyanisxyz." Could you add your fname here?

2023-04-21 20:09 UTC, Meyanis95 commented on apps/hubble/src/allowedPeers.mainnet.ts
> +  '12D3KooWEr4WoKduAQg8VJSgwcNsqptbdkSQLw1ceEr8oSBQurJX', // @meyanisxyz
Sorry it's @yanisme

2023-04-24 03:11 UTC, varunsrin commented on apps/hubble/src/allowedPeers.mainnet.ts
> +  '12D3KooWEr4WoKduAQg8VJSgwcNsqptbdkSQLw1ceEr8oSBQurJX', // @meyanisxyz
would you mind updating and rebasing to address the conflict?

2023-04-27 06:32 UTC, closed without merging