fix: improve handling of duplicate messages on gossip
farcasterxyz/hub-monorepo pull request #919
Opened 2023-04-26 15:53 UTC by sagar-a16z

fixes https://github.com/farcasterxyz/hub-monorepo/issues/904

## Motivation

Gossip should be able to de-duplicate Farcaster Protocol messages.

## Change Summary

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [x] PR has a [changeset](../CONTRIBUTING.md#35-adding-changesets)
- [x] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [x] PR does not require changes to the [protocol](https://github.com/farcasterxyz/protocol)
- [x] All [commits have been signed](../CONTRIBUTING.md#22-signing-commits)

---

## PR-Codex overview
This PR improves the handling of duplicate messages on gossip and updates the GossipSub protocol version to V1.1.

### Detailed summary
- Adds `GossipVersion.V1_1` to `protobufs/schemas/gossip.proto`.
- Updates `apps/hubble/src/network/utils/factories.ts` to use `GossipVersion.V1_1`.
- Adds `msgIdFnStrictSign` to `apps/hubble/src/network/p2p/protocol.ts`.
- Updates `apps/hubble/src/network/p2p/protocol.ts` to use `GossipVersion.V1_1`.
- Adds `GossipVersion.V1_1` to `packages/core/src/protobufs/generated/gossip.ts`.
- Updates `apps/hubble/src/test/e2e/gossipNetwork.test.ts` to use `await` and add new tests.
- Updates `apps/hubble/src/network/p2p/gossipNode.ts` to handle duplicate messages and publish results.

> The following files were skipped due to too many changes: `apps/hubble/src/network/p2p/gossipNode.ts`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2023-04-26 16:37 UTC, varunsrin requested changes

2023-04-26 17:22 UTC, sagar-a16z commented on .changeset/fresh-impalas-switch.md
> +'@farcaster/hubble': major
I misunderstood where the major came from. I'll fix that. 

But this is a breaking change. I can work on making it backward compatible but that will introdouce some throwaway work. I'll defer to you guys here. If you think I need to preserve backwards compatibility I can attempt it.

I'll need to maintain a list of acceptable GossipVersions and fallback to older logic when older version messages show up.

2023-04-26 19:37 UTC, varunsrin commented on .changeset/fresh-impalas-switch.md
> +'@farcaster/hubble': major
ok, i think its safe to merge in, @sanjayprabhu is going to review and then merge

2023-04-27 01:14 UTC, sanjayprabhu commented on .changeset/fresh-impalas-switch.md
> +'@farcaster/hubble': major
@sagar-a16z this is amazing, thanks for this. I do think it's worth making it backwards compatible and we can just release it as a patch upgrade. If you don't have time, let me know and I can do it sometime next week.

2023-04-27 16:13 UTC, sagar-a16z commented on .changeset/fresh-impalas-switch.md
> +'@farcaster/hubble': major
@sanjayprabhu this PR should now be backwards compatible.

2023-05-05 20:01 UTC, sanjayprabhu approved these changes
Looks good, thanks for making it backwards compatible.

2023-05-05 20:02 UTC, merged